# Site settings
title: yogi codes
header-img: img/home-bg.png
email: soljin01@gmail.com
copyright_name: jin501
description: > # this means to ignore newlines until "baseurl:"
  a technical blog, journeying through the world of programming..
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jin501
learn_profile: jin501
email_username: soljin01@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
